### PR TITLE
added edit recor command

### PR DESCRIPTION
**Pull request by OF3000**

### CODE REVIEW

**Comment by svilav** [comment]
I see several issues here:
* in `console_bot.py` we don't write low-level commands, so to adhere to the existing structure I'd move this functions to InputManager
* we already have commands to change phone, email, and address. It would be nice if you found a way to reuse those

**Comment by OF3000** [comment]
Agree, I'll move delete away from console_bot.

Regarding reusage existed  command, actualy I do so but need extra communication with end user to get index of sub-entity as well as record existing check, get_* command always returns some string, so I don't see other way to check it.

if you are ok with cnange_* command change I can add index input there, it should simplify code

**Comment by TetianaFilonenko** [comment]
One more thing that could be done that would simplify UX is to have one more command that delete record completely.

**Comment by OF3000** [comment]
I've moved deletion to input_manager. Also I've tried to go away from using record itself on console bot side, but it requires deeper changes on Record and Book classes to support this flow, I'm afraid we don't have enough time for me to complete it. Let's keep it as known area of improvement going forward.

**Comment by svilav** [comment]
Maybe lets create new file called `edit.py`, move all you added to `console_bot.py` there and only import them in `console_bot.py` for it to look a little bit cleaner

**Comment by OF3000** [comment]
nice idea, I've moved it to separate file

**Review by TetianaFilonenko — APPROVED** [review]

**Pull request merged**
